### ISSUE TITLE
hello, how can I run the script on 1366 x 768

### ISSUE THREAD

**Issue by yhaloo** [onoderis/bgc-script#2]
Can i run the script on 1366 x 768
im finding ways to bind the {F} button to Xbutton1. Not spam. 
had no prior knowledge of ahk or programming in general.
any help is greatly appreciated.
Thank you.

**Comment by onoderis** [comment]
@yhaloo Hi.
Right now you can't run the script with your resolution. I might add support for other resolutions in the future, but no promises.
If you want just to add additional binding for F key and you don't need the other features from the script, you can do it this way:

```ahk
XButton1::
    Send, {f}
return
```
Hope it helps.

**Comment by yhaloo** [comment]
I did use it yesterday.

XButton1::
    Send, {f}
return

While it does work when testing using notepad & word, it doesn't work when
playing genshin.

Thanks for replying tho.

**Comment by onoderis** [comment]
@yhaloo Have you run the script with administrator rights?

**Comment by yhaloo** [comment]
Just tried n it works, such a simple solution

Thanks broo
